### ISSUE TITLE
Redundant method

### ISSUE THREAD

**Issue by IanaKhitsko** [staysshen/euro-diffusion#4]
https://github.com/staysshen/euro-diffusion/blob/ab575b0a4d1ee31be27922cb13780d1409f2eb1d/models.py#LL142C9-L142C31

Why do you need this method at all? You use it only inside the class. The same for next method

**Comment by staysshen** [comment]
Були видалені методи get_initial_coin_count() та get_representative_portion(), а там де ці методи викликалися тепер використовуються просто класові змінні Algorithm.INITIAL_COIN_COUNT та Algorithm.REPRESENTATIVE_PORTION.
